### ISSUE TITLE
Add Update Command

### ISSUE THREAD

**Issue by vinkla** [vinkla/climb#1]
We want to be able to update the composer packages bu running:

```bash
climb update
```
And if we want to update to breaking versions:
```bash
climb update --all
```

**Comment by jenssegers** [comment]
Would you go `climb -u` or `climb upgrade`? Already prepared for adding `-u` like `ncu`: https://github.com/jenssegers/climb/commit/d086ce03b0d208633ec7db11ad21f9f3b895be11

**Comment by jenssegers** [comment]
But I wonder if the Ladder class should be responsible for the upgrade, or the command.

**Comment by vinkla** [comment]
Maybe a second command would be better in this case? Something like `climb update`. What do you think?

**Comment by vinkla** [comment]
I would go with the command instead of just -u, it is more readable to write it out.

**Comment by jenssegers** [comment]
Doesn't really matter I guess, I just copied ncu :)

**Comment by vinkla** [comment]
That is true :)
