### ISSUE TITLE
0.0.0 version

### ISSUE THREAD

**Issue by Rudloff** [vinkla/climb#12]
Climb suggests an odd 0.0.0 verison number:
```
$ climb

smarty/smarty     3.1.27     →     0.0.0
```

**Comment by vinkla** [comment]
Thanks for reporting! Probably is something with the version_compare method.

**Comment by elazar** [comment]
Probably related to the initial value in [this call](https://github.com/vinkla/climb/blob/b9019a33c003e5f636b80503f3a9481e42c26639/src/CheckCommand.php#L219). I admittedly didn't check to see how it would respond to that; it just seemed like the most reasonable value to use.

**Comment by vinkla** [comment]
Yeah, probably that is also why it sometimes return this as well:

```bash
5.1.17     →     5.1.9
```

**Comment by elazar** [comment]
@vinkla No, that's a different problem.

```
php -r 'var_dump(version_compare("5.1.17", "5.1.9", ">"));' => bool(true)
```

**Comment by vinkla** [comment]
Aah okay, maybe we should just remove anything but numbers and compare the values against each other then? Testing this and version_compare might do the job?

**Comment by elazar** [comment]
Perhaps. Maybe make [this line](https://github.com/vinkla/climb/blob/b9019a33c003e5f636b80503f3a9481e42c26639/src/CheckCommand.php#L231) of `CheckCommand->normalize()` more strict in what it returns, like so?

```php
$version = preg_replace('/[^0-9.]/', '', $version);
```

Looks like [related filtering](https://github.com/vinkla/climb/blob/b9019a33c003e5f636b80503f3a9481e42c26639/src/CheckCommand.php#L214) is being done in `CheckCommand->getLatest()`.

Seems like version normalization overall needs to be done in a more organized fashion within this class, maybe using [`Composer\Package\Version\VersionParser->normalize()`](https://github.com/composer/composer/blob/9f2e562e48145f10bf224f93f561e762df980638/src/Composer/Package/Version/VersionParser.php#L87-L171).

**Comment by jenssegers** [comment]
My last PR will fix the version compare issue.

**Comment by vinkla** [comment]
Merged
