### ISSUE TITLE
Non-zero exit code

### ISSUE THREAD

**Issue by le6o** [vinkla/climb#21]
If packages are upgradable or out of date then it would be useful for `climb` to exit with a non-zero status code.

*Ideal for CI tools.*

**Comment by vinkla** [comment]
Not sure I get what you mean. Could you explain a bit more? Thanks.

**Comment by jenssegers** [comment]
Can you think of a specific use case?

I don't think you want scripts to fail, just because you're stuck using an outdated package. Eg. if you're still using Laravel 4.x, and there's no business value in upgrading to 5.x.

**Comment by le6o** [comment]
> Can you think of a specific use case?

We'd like to automate this as much as possible with our CI tool (Jenkins).
An exit code would make this a lot simpler, especially when combined with #22 and #23

**Comment by vinkla** [comment]
@le6o maybe you could create a PR for this and then we can take it from there.

**Comment by juliangut** [comment]
Maybe a flag to allow/disallow failures on outdated packages could be usefull for CI integration.
What @jenssegers comments could be covered by the flag: if I know I'm using Laravel4 and that is something that won't change (your reason here) the failure can be disabled.
IMO outdated flag does have value for CI, on the contrary upgradable does not

**Comment by vinkla** [comment]
If you could make a PR for this @le6o then we can take it from there.

**Comment by juliangut** [comment]
@vinkla @le6o If you don't mind I'm currently working on implementing three flags

* `--outdated` to show only outdated packages
* `--upgradable` to show only upgradable packages
* `--fail` to `return 1` if outdated or/and upgradable

This way you can decide what to check (outdated, upgradable or both if no flag provided) and whether to fail if an action can be performed. I think this covers this issue and #23

**Comment by vinkla** [comment]
This is merged in master.
