### ISSUE TITLE
CLI flag to ignore pre-releases

### ISSUE THREAD

**Issue by le6o** [vinkla/climb#22]
It would be useful to ignore pre-releases such as alpha/beta/rc etc.

**Comment by vinkla** [comment]
IMO This is a great idea. Sometimes we want to be cutting edge using unstable latest version ;)

@jenssegers What do you think about this? Maybe we could implement something like `--with-unstable` or something similar.

**Comment by jenssegers** [comment]
As of now only `-dev` releases are ignored. For me it's quite useful to know if there's a new RC or beta version. But a flag could be handy, but what would be the default behaviour then :)

**Comment by vinkla** [comment]
I've excluded all unstable releases for now. I'll close this in favour of #36.
