### ISSUE TITLE
CLI flag to filter out upgrades/outdated

### ISSUE THREAD

**Issue by le6o** [vinkla/climb#23]
It would be useful to report only upgradable packages or only outdated packages.

When coupled with #21 and #22 you could easily configure a CI environment to warn about outdated packages or fail if upgrades are possible.

**Comment by vinkla** [comment]
Yeah, we could use just `--outdated` or `--upgradable` as flags for this. Great idea!

**Comment by vinkla** [comment]
This is merged in master.
