### ISSUE TITLE
Don't Remove Version Constraints

### ISSUE THREAD

**Issue by vinkla** [vinkla/climb#3]
Today we normalize all version to only contain numbers and dots but in the future we should check the version constraints as well.

**Comment by jenssegers** [comment]
I currently got the `climb` command to output this:

```
guzzlehttp/guzzle               5.3.0      →     6.1.0
laravel/framework               4.2.17     →     5.1.23
sensiolabs/security-checker     2.0.5      →     3.0.1

Run 'climb upgrade' to upgrade your composer.json

The following dependencies are satisfied by their declared version constraint, but the installed versions are behind. You can install the latest versions without modifying your composer.json file by using 'composer update'

lusitanian/oauth     0.8.1     →     0.8.2
```

**Comment by jenssegers** [comment]
I can do a PR today I you want this into climb.

**Comment by jenssegers** [comment]
Also made sure that dev versions are not included, and tweaked the diff function to work with strings of different lengths.

**Comment by vinkla** [comment]
You're awesome @jenssegers! We should also look into #16 with the RC versions.

**Comment by jenssegers** [comment]
That should be fixed in this PR.

**Comment by vinkla** [comment]
![awesome](http://i.giphy.com/Qh6NZWsFx1G1O.gif)
