### ISSUE TITLE
Incorrect update suggestion for beta version

### ISSUE THREAD

**Issue by bocharsky-bw** [vinkla/climb#37]
I get next update info:

```
symfony/console     2.7.6     →     3.0.0-BETA1
```

But my `composer.json` is:
```json
{
    "require": {
        "symfony/console": "~2.7",
        "fabpot/goutte": "~3.1"
    },
    "autoload": {
        "psr-4": {"": "src/"}
    }
}
```

And when I do `composer up` - there're no any available updates for me, because I get latest stable `2.7.6`. But Climb show me this update to beta. Does it a bug?

**Comment by vinkla** [comment]
Yeah, this is a bug we're aware of and will fix asap. This is also mentioned in #36.

**Comment by bocharsky-bw** [comment]
Oh, I don't notice it, thanks! Should we close this issue as dublicate?

**Comment by vinkla** [comment]
No, I think can leave it open until we fix it. Thanks for reporting btw!

**Comment by vinkla** [comment]
Fixed in version `0.6.1`.

**Comment by bocharsky-bw** [comment]
Nice! Thanks!

**Comment by vinkla** [comment]
We're going to make this even better in future version. Check out #36 for more info.
