### ISSUE TITLE
Skip or ignore failures for custom repo packages

### ISSUE THREAD

**Issue by jenssegers** [vinkla/climb#4]
In my project I'm using a custom package that is linked to a repository. When running climb it throws this error because it is not on packagist:

```
  [Guzzle\Http\Exception\ClientErrorResponseException]  
  Client error response                                 
  [status code] 404                                     
  [reason phrase] Not Found                             
  [url] https://packagist.org/packages/acme/foo.json 
```

I would either ignore these 404 errors or try to skip custom packages. Unless you can find a way to get the git tags for these packages ;)

**Comment by vinkla** [comment]
Thats true, git tags might be a better approach. I'll look into this, for now maybe we could just skip the packages that return 404. Thanks for reporting!

**Comment by vinkla** [comment]
@jenssegers This has now been fixed.

**Comment by jenssegers** [comment]
Thanks :)

**Comment by vinkla** [comment]
Anytime :)
