### ISSUE TITLE
Exclude packages

### ISSUE THREAD

**Issue by juliangut** [vinkla/climb#45]
What are your thoughts on adding a flag to define a list of packages to be excluded from being checked?

```
--exclude=phpunit/phpunit,laravel/homestead
```

**Comment by vinkla** [comment]
Yeah, maybe. What is the use case? I don't really want to make it to bloated but if it fills a purpose I think it is fine to add this.

**Comment by juliangut** [comment]
The use case is an extension of reciently merged #43. There is the --no-upgradable flag but what if I have one dependency I don't want to be checked because I must stick with it but I want the rest checked.

More specifically in my current case: I'm using phpunit:^4.8 because can't update to 5. I want the rest of the deps checked but phpunit

**Comment by vinkla** [comment]
Okay, sounds legit. Could you make a pull request?

**Comment by juliangut** [comment]
Sure, when I reach a computer, I'm on the cell now
