### ISSUE TITLE
Update required dev packages

### ISSUE THREAD

**Issue by damnedest** [vinkla/climb#47]
If you run climb and there is outdated package from require dev then climb moves in to normal requires

**Comment by vinkla** [comment]
When you run `climb update`?

**Comment by damnedest** [comment]
Yep =)

**Comment by damnedest** [comment]
`climb update --all`

**Comment by vinkla** [comment]
Thanks for reporting! I'll look in to this.

**Comment by vinkla** [comment]
I've pushed a update to the master branch. Do you think you could test it?

**Comment by damnedest** [comment]
Thanks for update. Looks great and works.

**Comment by vinkla** [comment]
Great. Thanks!
