### ISSUE TITLE
Add composer.lock

### ISSUE THREAD

**Issue by mbrodala** [vinkla/climb#48]
To avoid accidental breakage due to updated dependencies, the `composer.lock` should be added to the repository.

**Comment by vinkla** [comment]
That is true, I'll add it. Thanks!

**Comment by jenssegers** [comment]
I don't agree.

**Comment by vinkla** [comment]
@jenssegers why not?

**Comment by jenssegers** [comment]
For applications yes, but for packages like this it's not necessary as `composer global install` will completely ignore the lock file.

**Comment by vinkla** [comment]
Yeah, but isn't it legit with the `composer.lock` file?

**Comment by mbrodala** [comment]
@jenssegers Please have a look at the [Composer docs](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file): _Commit your application's composer.lock (along with composer.json) into version control._

This is not about a global installation or installation as dependency but for the case if you want to develop on this repository itself.

**Comment by jenssegers** [comment]
I agree for applications. But not on packages.

**Comment by vinkla** [comment]
Isn't this an application?

**Comment by mbrodala** [comment]
Imagine developer A starts developing on climb, performs a `composer install` and gets all dependencies installed. Now developer B does the same but gets a newer version e.g. of `symfony/console` which contains a bug. The `composer.lock` could prevent this.

**Comment by mbrodala** [comment]
General rule of thumb: *always* add the `composer.lock` to your project; there is no reason not to add it but good reason to do it. You do not lose any thing if you do.

**Comment by vinkla** [comment]
Yeah, for packages we should definitely remove the `composer.lock` file. But do we consider this a package of application?

**Comment by jenssegers** [comment]
If you install `climb` using composer, the lock file will be ignored anyway, so it's better to have a locked down `composer.json` file. The only thing the lock file can have an impact on is the phar application binary. But as @vinkla is the only one currently building them on each release that should not cause a big issue.

**Comment by prisis** [comment]
For me it is a application, so :+1: composer.lock

**Comment by vinkla** [comment]
@jenssegers good point!

**Comment by mbrodala** [comment]
@jenssegers A locked down `composer.json` duplicates the purpose of the `composer.lock`. Again, there is only gain from adding the `composer.lock` and nothing lost. The main gains:

* Avoid accidental breakage on unintential dependency version bump
* Vastly speed up dependency installation (development, CI builds, ...)

We had a similar (and long) discussion in TYPO3 about this and the verdict was that everyone got why it's useful and the file was added.

**Comment by mbrodala** [comment]
@vinkla What's your decision on this one? I've laid out the facts I see, there may be more but everything else is up to you.

**Comment by vinkla** [comment]
@mbrodala haven't decided yet. Let me think about it.

**Comment by vinkla** [comment]
@mbrodala thanks for your suggestion but I've decided to pass on this. As @jenssegers says, I'm the only one who will build the phar.

**Comment by mbrodala** [comment]
Alright, gotcha. :-)
