### ISSUE TITLE
Double vs singe digit versions not compared correctly?

### ISSUE THREAD

**Issue by elazar** [vinkla/climb#5]
Examples:
```
monolog/monolog               1.12          →     1.9.
nesbot/Carbon                 1.13          →     1.9.
```

**Comment by vinkla** [comment]
Yeah, we need to add comparison if the version number is lower. I'll fix this asap. Thanks for reporting!

**Comment by elazar** [comment]
@vinkla Any particular reason that [`CheckCommand->compare()`](https://github.com/vinkla/climb/blob/8f29791311e1590007c7f5626c3fd38c040ad154/src/Commands/CheckCommand.php#L179-L200) doesn't just use [`version_compare()`](http://php.net/manual/en/function.version-compare.php)?

**Comment by vinkla** [comment]
To be honest I had no idea it existed. Thanks for sharing!

**Comment by elazar** [comment]
@vinkla FYI, it looks like Composer already has a [method for normalizing package versions](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L95). I think versions returned by this should be usable with `version_compare()`.

**Comment by vinkla** [comment]
Thats cool, maybe we should integrate that instead. It would be a lot easier if we didn't have to build that on our own. Thanks!

**Comment by vinkla** [comment]
This has now been fixed. Thanks for reporting the bug!

**Comment by elazar** [comment]
This doesn't appear to have been fixed. :( I've updated climb to 0.1.3 and the bug still occurs.

**Comment by vinkla** [comment]
Ahh okay, to bad :( Any ideas why?

**Comment by elazar** [comment]
`getLatest()` [isn't actually finding the latest version](https://github.com/vinkla/climb/blob/26957c798379815c3395f241e450a54a36735987/src/Commands/CheckCommand.php#L150-L157). Something like this should work:

```php
private function getLatest(array $versions)
{
    return array_reduce(
        $versions,
        function($carry, $item) {
            return version_compare($carry, $item, '>') ? $carry : $item;
        },
        '0.0.0'
    );
}
```

**Comment by vinkla** [comment]
Pushed to 0.1.4 https://github.com/vinkla/climb/releases/tag/0.1.4
