### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by elazar** [vinkla/climb#7]
I'd like to be able to easily pull in the fix for #5 without having to resort to something like aliasing the next version to dev-master in my composer.json file. I'd recommend frequent tags, even if they're only mini releases, until this tool gets to a stable 1.0 release.

**Comment by vinkla** [comment]
Sure thing, I'll fix this asap. Btw, you can use `1.0.*@dev` to always have the latest changes. Though, then you will always get the latest changes on the master branch.

**Comment by vinkla** [comment]
Done https://github.com/vinkla/climb/releases/tag/0.1.1
